
import React, { useEffect, useRef } from 'react';
import { ChatMessage } from '../types';
import { User, Sparkles, Copy, Check, ExternalLink, Quote, AlertTriangle } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import remarkGfm from 'remark-gfm';
import 'katex/dist/katex.min.css';

declare const mermaid: any;

interface ChatMessageItemProps {
  message: ChatMessage;
  isStreaming?: boolean;
}

const ChatMessageItem: React.FC<ChatMessageItemProps> = ({ message, isStreaming = false }) => {
  const isUser = message.role === 'user';
  const [copied, setCopied] = React.useState(false);
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    let isMounted = true;
    const timeouts: number[] = [];

    if (!isUser && !isStreaming && containerRef.current) {
      const renderDiagrams = async () => {
        if (!isMounted || !containerRef.current) return;

        if (typeof mermaid === 'undefined') {
          const timeout = window.setTimeout(renderDiagrams, 500);
          timeouts.push(timeout);
          return;
        }

        const isDark = document.documentElement.classList.contains('dark');
        
        try {
          // Initialize mermaid with specific settings for speed and stability
          mermaid.initialize({ 
            startOnLoad: false, 
            theme: isDark ? 'dark' : 'neutral',
            securityLevel: 'loose',
            fontFamily: 'Inter',
            logLevel: 5,
            flowchart: { useMaxWidth: true, htmlLabels: true, curve: 'basis' },
            suppressErrorDisplay: true
          });
          
          const diagrams = containerRef.current?.querySelectorAll('.mermaid');
          if (!diagrams) return;

          for (let idx = 0; idx < diagrams.length; idx++) {
            if (!isMounted || !containerRef.current) break;
            
            const el = diagrams[idx] as HTMLElement;
            if (!el) continue;

            let code = el.getAttribute('data-code') || '';
            if (code) {
          // AUTO-CORRECTION: Strip hallucinated syntax keywords often generated by LLMs
          code = code.replace(/grid-layout/g, ''); 
          code = code.replace(/subgraph grid/g, 'subgraph');
          
          // Ensure it starts with a valid graph type if missing
          if (!code.trim().match(/^(graph|flowchart|sequenceDiagram|classDiagram|stateDiagram|erDiagram|journey|gantt|pie|quadrantChart|xychart|mindmap|timeline)/i)) {
            code = 'graph TD\n' + code;
          }

          // Fix unquoted labels with special characters (common LLM mistake)
          let subgraphCounter = 1;
          code = code.split('\n').map(line => {
            // Ensure subgraph has a valid ID and label
            if (line.trim().toLowerCase() === 'subgraph') {
              return `subgraph Section${subgraphCounter++} ["Section"]`;
            } else if (line.trim().toLowerCase().startsWith('subgraph ') && !line.includes('[')) {
              // If it's like `subgraph Something`, make it `subgraph id ["Something"]`
              const name = line.trim().substring(9).trim().replace(/["']/g, '');
              return `subgraph Sub${subgraphCounter++} ["${name}"]`;
            }
            
            if (line.includes('[') && !line.includes('"')) {
              line = line.replace(/\[(.*?)\]/g, '["$1"]');
            }
            if (line.includes('(') && !line.includes('"') && !line.includes('graph') && !line.includes('flowchart')) {
              line = line.replace(/\((.*?)\)/g, '("$1")');
            }
            
            // Fix link text syntax (convert `-- "text" -->` to `-->|"text"|`)
            line = line.replace(/--\s*"([^"]+)"\s*-->/g, '-->|"$1"|');
            line = line.replace(/--\s*"([^"]+)"\s*---/g, '---|"$1"|');
            line = line.replace(/-\.\s*"([^"]+)"\s*\.->/g, '-.->|"$1"|');
            line = line.replace(/-\.\s*"([^"]+)"\s*-\.-/g, '-.-|"$1"|');
            line = line.replace(/==\s*"([^"]+)"\s*==>/g, '==>|"$1"|');
            line = line.replace(/==\s*"([^"]+)"\s*===/g, '===|"$1"|');
            
            // Fix unquoted link text
            line = line.replace(/--\s+(.*?)\s+-->/g, '-->|"$1"|');
            line = line.replace(/--\s+(.*?)\s+---/g, '---|"$1"|');
            line = line.replace(/-\.\s+(.*?)\s+\.->/g, '-.->|"$1"|');
            line = line.replace(/-\.\s+(.*?)\s+-\.-/g, '-.-|"$1"|');
            line = line.replace(/==\s+(.*?)\s+==>/g, '==>|"$1"|');
            line = line.replace(/==\s+(.*?)\s+===/g, '===|"$1"|');
            
            // Fix single dash arrows which are invalid in flowchart
            if (code.includes('graph ') || code.includes('flowchart ')) {
              line = line.replace(/([A-Za-z0-9_"])\s*->\s*([A-Za-z0-9_"])/g, '$1 --> $2');
            }
            
            return line;
          }).join('\n');

          // Ensure all subgraphs are closed
          const subgraphCount = (code.match(/subgraph/g) || []).length;
          const endCount = (code.match(/\bend\b/g) || []).length;
          if (subgraphCount > endCount) {
            for (let i = 0; i < subgraphCount - endCount; i++) {
              code += '\nend';
            }
          }

          try {
            // Validate syntax first to prevent mermaid from injecting global error overlays
            if (mermaid.parse) {
              await mermaid.parse(code, { suppressErrors: true });
            }
            
            // Use a unique ID for each render to avoid collisions
            const id = `mermaid-${message.id}-${idx}-${Date.now()}`;
            
            // Create a temporary container so mermaid doesn't pollute the document body with errors
            const tempContainer = document.createElement('div');
            const { svg } = await mermaid.render(id, code, tempContainer);
            el.innerHTML = svg;
          } catch (err: any) {
            // Silence rendering errors for partial/malformed diagrams
            
            // Robust cleanup for Mermaid error overlays
            const cleanupMermaidErrors = () => {
              document.querySelectorAll('svg').forEach(svg => {
                const content = svg.innerHTML || '';
                if (content.includes('Syntax error') || content.includes('mermaid version') || svg.id.includes('dmermaid')) {
                  svg.remove();
                }
              });
              document.querySelectorAll('.error-icon').forEach(el => el.remove());
            };
            
            cleanupMermaidErrors();
            // Run again slightly later in case mermaid delays the injection
            setTimeout(cleanupMermaidErrors, 50);
            setTimeout(cleanupMermaidErrors, 200);

            // Show the raw code in a pre block if it fails, so user can see what's wrong
            el.innerHTML = `
              <div class="flex flex-col items-center justify-center p-8 bg-slate-100/50 dark:bg-slate-800/50 rounded-3xl border border-dashed border-red-300 dark:border-red-700">
                <AlertTriangle size={24} className="text-red-500 mb-2" />
                <p class="text-[10px] font-black text-red-500 uppercase tracking-widest text-center">Syntax Error in Diagram</p>
                <pre class="text-[9px] font-mono text-slate-500 mt-4 p-4 bg-white dark:bg-slate-900 rounded-xl overflow-x-auto max-w-full">${code}</pre>
              </div>
            `;
          }
        }
      }
    } catch (err) {
      console.error("Mermaid initialization failed", err);
    }
  };

    renderDiagrams();
    }

    return () => {
      isMounted = false;
      timeouts.forEach(t => window.clearTimeout(t));
    };
  }, [message.content, isUser, isStreaming]);

  const renderContent = (content: string) => {
    return (
      <div className="markdown-body text-sm md:text-lg font-medium text-slate-700 dark:text-slate-200 leading-relaxed selection:bg-indigo-500/20">
        <ReactMarkdown
          remarkPlugins={[remarkMath, remarkGfm]}
          rehypePlugins={[rehypeKatex]}
          components={{
            code({ node, inline, className, children, ...props }: any) {
              const match = /language-(\w+)/.exec(className || '');
              if (!inline && match && match[1] === 'mermaid' && !isStreaming) {
                return (
                  <div className="my-8 p-6 bg-slate-50/50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-800 rounded-[2rem] shadow-inner overflow-x-auto">
                    <div className="mermaid flex justify-center w-full min-w-[300px]" data-code={String(children).replace(/\n$/, '')}></div>
                    <p className="text-[9px] text-center text-indigo-500 font-black uppercase tracking-[0.3em] mt-6 opacity-60">Architectural Synthesis</p>
                  </div>
                );
              }
              return (
                <code className={`${className} bg-slate-100 dark:bg-slate-800 px-1.5 py-0.5 rounded-md text-sm font-mono text-indigo-600 dark:text-indigo-400`} {...props}>
                  {children}
                </code>
              );
            },
            table({ children }) {
              return (
                <div className="overflow-x-auto my-6 rounded-2xl border border-slate-200 dark:border-slate-700 shadow-sm bg-white dark:bg-slate-900/50">
                  <table className="min-w-full border-collapse text-left">{children}</table>
                </div>
              );
            },
            th({ children }) {
              return <th className="px-4 py-3 text-left text-xs font-black text-slate-500 dark:text-slate-400 uppercase tracking-wider border-b border-slate-200 dark:border-slate-700 bg-slate-50/50 dark:bg-slate-800/50">{children}</th>;
            },
            td({ children }) {
              return <td className="px-4 py-3 text-sm text-slate-700 dark:text-slate-300 border-b border-slate-100 dark:border-slate-800/50">{children}</td>;
            },
            strong({ children }) {
              return <strong className="text-indigo-900 dark:text-indigo-400 font-black underline decoration-indigo-500/20 underline-offset-4">{children}</strong>;
            },
            ul({ children }) {
              return <ul className="list-none space-y-2 my-4">{children}</ul>;
            },
            ol({ children }) {
              return <ol className="list-decimal pl-6 space-y-2 my-4 text-indigo-600 dark:text-indigo-500 font-black">{children}</ol>;
            },
            li({ children, node, ...props }: any) {
              if (node?.parent?.tagName === 'ul') {
                return (
                  <li className="flex items-start">
                    <span className="text-indigo-500 mr-2 mt-0.5">✦</span>
                    <span className="text-slate-700 dark:text-slate-200 font-medium">{children}</span>
                  </li>
                );
              }
              return (
                <li className="pl-2">
                  <span className="text-slate-700 dark:text-slate-200 font-medium">{children}</span>
                </li>
              );
            },
            p({ children }) {
              return <p className="my-4">{children}</p>;
            },
            h1({ children }) { return <h1 className="text-2xl font-black text-slate-900 dark:text-white mt-8 mb-4">{children}</h1>; },
            h2({ children }) { return <h2 className="text-xl font-black text-slate-900 dark:text-white mt-6 mb-3">{children}</h2>; },
            h3({ children }) { return <h3 className="text-lg font-bold text-slate-900 dark:text-white mt-4 mb-2">{children}</h3>; },
          }}
        >
          {content}
        </ReactMarkdown>
      </div>
    );
  };

  const renderVisual = (imageUrl: string) => (
    <div className="my-10 space-y-6 w-full animate-in fade-in zoom-in duration-1000">
      <div className="relative group rounded-[2.5rem] overflow-hidden shadow-2xl ring-4 ring-white/50 dark:ring-slate-800/50 bg-white dark:bg-slate-950 flex items-center justify-center">
        <img 
          src={imageUrl} 
          alt="Educational Synthesis" 
          className="w-full max-h-[70vh] object-contain transform transition-transform duration-700 group-hover:scale-[1.02]" 
          loading="lazy"
        />
        <a 
          href={imageUrl} 
          download="academic-visual.png"
          className="absolute inset-0 bg-indigo-900/40 opacity-0 group-hover:opacity-100 transition-all flex items-center justify-center text-white font-black gap-3 text-xs uppercase tracking-widest backdrop-blur-sm"
        >
          <ExternalLink size={20} />
          Archive to Study Vault
        </a>
      </div>
      <p className="text-[10px] text-center text-indigo-500 font-black uppercase tracking-[0.3em] opacity-60">High-Fidelity Visual Index</p>
    </div>
  );

  const renderWithVisuals = (content: string, imageUrl: string | null) => {
    if (!imageUrl) return renderContent(content);

    const placeholder = "[VISUAL]";
    if (content.includes(placeholder)) {
      const parts = content.split(placeholder);
      return (
        <div className="space-y-4">
          {parts.map((part, index) => (
            <React.Fragment key={index}>
              {part.trim() && renderContent(part)}
              {index === 0 && renderVisual(imageUrl)}
            </React.Fragment>
          ))}
        </div>
      );
    }

    // Fallback: append image at the end if no placeholder found
    return (
      <>
        {renderContent(content)}
        {renderVisual(imageUrl)}
      </>
    );
  };

  const formatTime = (timestamp: any) => {
    if (!timestamp) return '';
    try {
      const date = timestamp.toDate ? timestamp.toDate() : new Date(timestamp);
      if (isNaN(date.getTime())) return '';
      return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    } catch (e) {
      return '';
    }
  };

  return (
    <div ref={containerRef} className={`flex gap-4 md:gap-8 animate-in fade-in slide-in-from-bottom-4 duration-700 fill-mode-both ${isUser ? 'flex-row-reverse' : 'flex-row'}`}>
      <div className={`w-12 h-12 md:w-16 md:h-16 rounded-3xl flex items-center justify-center flex-shrink-0 shadow-2xl transform transition-all hover:scale-110 relative ${
        isUser ? 'bg-slate-900 dark:bg-slate-800 text-white' : 'bg-indigo-600 text-white overflow-hidden'
      }`}>
        {isUser ? <User size={24} /> : (
          <>
            <div className="absolute inset-0 bg-gradient-to-tr from-indigo-700 to-indigo-400 animate-pulse"></div>
            <Sparkles size={24} className="relative z-10" />
          </>
        )}
      </div>
      
      <div className={`max-w-[85%] md:max-w-[80%] flex flex-col ${isUser ? 'items-end' : 'items-start'}`}>
        <div className={`p-6 md:p-10 rounded-[3rem] border transition-all relative group ${
          isUser 
            ? 'bg-white dark:bg-slate-900 text-slate-800 dark:text-slate-200 rounded-tr-none border-slate-200 dark:border-slate-800 shadow-xl' 
            : 'bg-white/80 dark:bg-slate-900/80 backdrop-blur-xl text-slate-900 dark:text-slate-100 rounded-tl-none border-white/50 dark:border-white/5 shadow-2xl ring-1 ring-indigo-500/10'
        }`}>
          {!isUser && <Quote className="absolute -top-4 -left-4 text-indigo-600/10 w-16 h-16 pointer-events-none" />}
          
          {message.content && renderWithVisuals(message.content, message.imageUrl || null)}
          
          {!isUser && (
             <div className="mt-8 pt-6 border-t border-slate-100 dark:border-slate-800/50 flex justify-between items-center">
                <div className="flex items-center gap-3">
                  <div className="w-2 h-2 bg-indigo-500 rounded-full animate-pulse shadow-[0_0_10px_#6366f1]"></div>
                  <span className="text-[10px] font-black text-indigo-500 uppercase tracking-widest">Mentor Insight Verified</span>
                </div>
                <button 
                  onClick={() => {
                    navigator.clipboard.writeText(message.content);
                    setCopied(true);
                    setTimeout(() => setCopied(false), 2000);
                  }}
                  className="p-2 text-slate-300 hover:text-indigo-500 transition-colors"
                >
                  {copied ? <Check size={18} className="text-emerald-500" /> : <Copy size={18} />}
                </button>
             </div>
          )}
        </div>
        <div className={`mt-3 px-6 flex items-center gap-2 opacity-40 group-hover:opacity-100 transition-opacity`}>
          <span className="text-[9px] font-black text-slate-400 uppercase tracking-[0.2em]">
            {formatTime(message.timestamp)}
          </span>
        </div>
      </div>
    </div>
  );
};

export default ChatMessageItem;
